apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todoapp
spec:
  serviceName: todoapp-svc
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: db-secret
      containers:
        - name: todo
          imagePullPolicy: Always
          image: PROJECT/IMAGE-TODOAPP
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 7
            httpGet:
              port: 4444
              path: /healthz
          livenessProbe:
            initialDelaySeconds: 25
            periodSeconds: 7
            httpGet:
              port: 4444
              path: /healthz
          resources:
            limits:
              cpu: "100m"
              memory: "150Mi"
          envFrom:
            - secretRef:
                name: db-secret
          env:
            - name: HOST
              value: postgres-svc
---