apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job-fetch-read-todo
  namespace: my-project
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: fetch-todo-cron-job
              image: dievskiy/fetch-todo:v1
              imagePullPolicy: Always
          restartPolicy: OnFailure