apiVersion: batch/v1
kind: Job
metadata:
  name: fetch-read-todo
  namespace: my-project
spec:
  template:
    spec:
      containers:
        - name: fetch-todo
          image: dievskiy/fetch-todo:v1
      restartPolicy: Never