apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- todoapp-service.yaml
- todoapp-stateful_set.yaml
- pingpong-analysistemplate.yaml
- pingpong_service.yaml
- pingpong-deployment.yaml
- logoutput-analysistemplate.yaml
- logoutput-configmap.yaml
- logoutput-deployment.yaml
- broadcaster-deployment.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: dievskiy/todoapp
  newTag: 1440406592cef6200e35336a2959a36f42890113
- name: PROJECT/IMAGE-BROADCASTER
  newName: dievskiy/broadcaster
  newTag: c2af3bdc32fcce37651be57d273dcf4b9f188851
- name: PROJECT/IMAGE-LOG-OUTPUT
  newName: dievskiy/log-output
  newTag: c2af3bdc32fcce37651be57d273dcf4b9f188851
- name: PROJECT/IMAGE-PINGPONG
  newName: dievskiy/pingpong
  newTag: c2af3bdc32fcce37651be57d273dcf4b9f188851
- name: PROJECT/IMAGE-TODOAPP
  newName: dievskiy/todoapp
  newTag: c2af3bdc32fcce37651be57d273dcf4b9f188851
