apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: dievskiy/dwk-4-gitops-app
  newTag: 69c10ead0cb733e08a85dc3c7c1663f1f0bb596c
