apiVersion: v1
kind: Service
metadata:
  name: log-output-v203-svc
  namespace: my-project
spec:
  type: ClusterIP
  selector:
    app: ex-203
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3333