apiVersion: v1
kind: Service
metadata:
  name: todoapp-v1-svc
  namespace: my-project
spec:
  type: ClusterIP
  selector:
    app: ex-203
  ports:
    - port: 1010
      protocol: TCP
      targetPort: 4444