apiVersion: v1
kind: Service
metadata:
  name: pingpong-v3-svc
  namespace: my-project
spec:
  type: ClusterIP
  selector:
    app: ex-203
  ports:
    - port: 1111
      protocol: TCP
      targetPort: 5555