apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/logoutput.yaml
  - manifests/configmap.yaml
  - manifests/logoutput_service.yaml
  - manifests/analysistemplate.yaml
#  - manifests/horizontalpodautoscaler.yaml # comment out to save some RAM on local setup
images:
  - name: PROJECT/IMAGE-LOG-OUTPUT
    newName: dievskiy/log-output:v19