apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/logoutput.yaml
  - manifests/configmap.yaml
  - manifests/ingress.yaml
  - manifests/logoutput_service.yaml
  - manifests/pingpon_service.yaml
images:
  - name: PROJECT/IMAGE-LOG-OUTPUT
    newName: dievskiy/log-output:v18
  - name: PROJECT/IMAGE-PINGPONG
    newName: dievskiy/pingpong:v7