apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/service.yaml
  - manifests/route.yaml
images:
  - name: PROJECT/IMAGE-PINGPONG
    newName: dievskiy/pingpong:v10