apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todoapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: todoapp
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70