apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-claim
  namespace: my-project
spec:
  storageClassName: project
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi