apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/service.yaml
  - manifests/stateful_set.yaml
#  - manifests/horizontalpodautoscaler.yaml # comment out to save some RAM on local setup
images:
  - name: PROJECT/IMAGE-TODOAPP
    newName: dievskiy/todoapp:v8