apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- stateful_set.yaml
#  - horizontalpodautoscaler.yaml # comment out to save some RAM on local setup
images:
- name: IMAGE_PLACEHOLDER
  newName: dievskiy/todoapp
  newTag: 672491ac00d62016bf6da3efc2b5150eb8932c13
- name: PROJECT/IMAGE-TODOAPP
  newName: dievskiy/todoapp:v10
