apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- stateful_set.yaml
#  - horizontalpodautoscaler.yaml # comment out to save some RAM on local setup
images:
- name: IMAGE_PLACEHOLDER
  newName: dievskiy/todoapp
  newTag: cbbb8cd42ff312177c561fc6690b2be6b22dcc49
- name: PROJECT/IMAGE-TODOAPP
  newName: dievskiy/todoapp:v10
