apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/service.yaml
  - manifests/stateful_set.yaml
  - manifests/horizontalpodautoscaler.yaml
images:
  - name: PROJECT/IMAGE-TODOAPP
    newName: dievskiy/todoapp:v5