apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: log-output-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: log-output
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60