apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/pingpong_service.yaml
  - manifests/deployment.yaml
images:
  - name: PROJECT/IMAGE-PINGPONG
    newName: dievskiy/pingpong:v8