apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          imagePullPolicy: Always
          image: dievskiy/pingpong:v1