apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-v7-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          imagePullPolicy: Always
          image: dievskiy/log-output:v7-8