apiVersion: v1
kind: Service
metadata:
  name: log-reader-v1-svc
spec:
  type: ClusterIP
  selector:
    app: app12-reader-and-writer
  ports:
    - port: 1111
      protocol: TCP
      targetPort: 5555