name: Release 4-gitops-app

on:
  push:
    branches:
      - main
    paths:
      - 'part-4/gitops-project/**'
      - '.github/workflows/gitops-project.yaml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push log-output
        uses: docker/build-push-action@v3
        with:
          context: part-4/gitops-project/logoutput
          push: true
          tags: dievskiy/log-output:${{ github.sha }}

      - name: Build and Push broadcaster
        uses: docker/build-push-action@v3
        with:
          context: part-4/gitops-project/broadcaster
          push: true
          tags: dievskiy/broadcaster:${{ github.sha }}

      - name: Build and Push todoapp
        uses: docker/build-push-action@v3
        with:
          context: part-4/gitops-project/todoapp
          push: true
          tags: dievskiy/todoapp:${{ github.sha }}

      - name: Build and Push pingpongapp
        uses: docker/build-push-action@v3
        with:
          context: part-4/gitops-project/pingpong
          push: true
          tags: dievskiy/pingpong:${{ github.sha }}


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      # Set up kustomize
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1

      # Update yamls
      - name: Update yamls for todoapp
        working-directory: part-4/gitops-project/manifests
        run: |-
          kustomize edit set image PROJECT/IMAGE-TODOAPP=dievskiy/todoapp:${{ github.sha }}
          kustomize edit set image PROJECT/IMAGE-LOG-OUTPUT=dievskiy/log-output:${{ github.sha }}
          kustomize edit set image PROJECT/IMAGE-PINGPONG=dievskiy/pingpong:${{ github.sha }}
          kustomize edit set image PROJECT/IMAGE-BROADCASTER=dievskiy/broadcaster:${{ github.sha }}

      # Commit and push
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'part-4/gitops-project/manifests/kustomization.yaml'
          message: New version release for gitops-app ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
